#!/usr/bin/env python

#    -- VRDG --
#
#    Copyright 2026 UAA Software
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
#    associated documentation files (the "Software"), to deal in the Software without restriction,
#    including without limitation the rights to use, copy, modify, merge, publish, distribute,
#    sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
#    NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
#    OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#    CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import os, sys, re, glob

# ------------------------------------------------ Config & Globals -------------------------------------------------------------

CURTASK_SOURCE = ""
CURTASK_NAME = ""
CURTASK_TYPE = "graphics"
CURTASK_IO = []
CURTASK_CREATE = []
CURTASK_CPU_PROFILE = ""
CURTASK_GPU_PROFILE = ""
CURTASK_FUNC = ""

OUTPUT_FILE_BUFFER = [
    "// This file is generated by %s. DO NOT EDIT!!!\n\n"
    % os.path.basename(sys.argv[0]),
    "#pragma once\nnamespace vrdg {\n",
]

IOTYPE_TO_FUNCTIONARG = {}
IOTYPE_TO_FUNCTIONARG["Write_Buffer"] = "Buffer"
IOTYPE_TO_FUNCTIONARG["Read_Buffer"] = "Buffer"
IOTYPE_TO_FUNCTIONARG["Write_TextureFB"] = "FrameBuffer"
IOTYPE_TO_FUNCTIONARG["Read_TextureFB"] = "FrameBuffer"
IOTYPE_TO_FUNCTIONARG["Create_Buffer"] = "Buffer&"
IOTYPE_TO_FUNCTIONARG["Create_TextureFB"] = "FrameBuffer&"

IOTYPE_TO_ENGINE_FUNCTIONARG = {}
IOTYPE_TO_ENGINE_FUNCTIONARG["Write_Buffer"] = "VRDG_BUFFER"
IOTYPE_TO_ENGINE_FUNCTIONARG["Read_Buffer"] = "VRDG_BUFFER"
IOTYPE_TO_ENGINE_FUNCTIONARG["Write_TextureFB"] = "VRDG_FRAMEBUFFER"
IOTYPE_TO_ENGINE_FUNCTIONARG["Read_TextureFB"] = "VRDG_FRAMEBUFFER"
IOTYPE_TO_ENGINE_FUNCTIONARG["Create_Buffer"] = "VRDG_BUFFER"
IOTYPE_TO_ENGINE_FUNCTIONARG["Create_TextureFB"] = "VRDG_FRAMEBUFFER"

IOTYPE_TO_ATTACH = {}
IOTYPE_TO_ATTACH["Write_Buffer"] = "VRDG_TYPE_BUFFER"
IOTYPE_TO_ATTACH["Read_Buffer"] = "VRDG_TYPE_BUFFER"
IOTYPE_TO_ATTACH["Write_TextureFB"] = "VRDG_TYPE_FB"
IOTYPE_TO_ATTACH["Read_TextureFB"] = "VRDG_TYPE_FB"
IOTYPE_TO_ATTACH["Create_Buffer"] = "VRDG_TYPE_BUFFER"
IOTYPE_TO_ATTACH["Create_TextureFB"] = "VRDG_TYPE_FB"

# ---------------------------------------------------- Helper functions ----------------------------------------------------------


def _extract_args_segment(line):
    start = line.find("(")
    if start == -1:
        return ""

    depth = 0
    for i in range(start, len(line)):
        ch = line[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return line[start + 1 : i]

    return line[start + 1 :]


def _split_args(segment):
    args = []
    buf = []
    depth = 0
    for ch in segment:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1

        if ch == "," and depth == 0:
            args.append("".join(buf).strip())
            buf = []
            continue

        buf.append(ch)

    tail = "".join(buf).strip()
    if tail or segment.strip():
        args.append(tail)

    return args


def getLineArguments(line):
    segment = _extract_args_segment(line)
    if not segment:
        return []
    return _split_args(segment)


# -------------------------------------------------- Render Graph Codegen -----------------------------------------------------------


def getSeparator(args):
    if len(args) > 0:
        return ", "
    return ""


def generateCurrentTask():
    callArgs = []
    inputArgs = []
    inputEngineArgs = []
    for t, name, args in CURTASK_IO:
        inputArgs.append(IOTYPE_TO_FUNCTIONARG[t] + " " + name)
        inputEngineArgs.append(IOTYPE_TO_ENGINE_FUNCTIONARG[t] + " " + name)
        callArgs.append(name)
    for t, name, args in CURTASK_CREATE:
        inputArgs.append(IOTYPE_TO_FUNCTIONARG[t] + " " + name)

    if len(CURTASK_FUNC) > 0:
        OUTPUT_FILE_BUFFER.append("// %s" % CURTASK_SOURCE)
        OUTPUT_FILE_BUFFER.append(
            "void %s( %s );" % (CURTASK_FUNC, ", ".join(inputEngineArgs))
        )
        OUTPUT_FILE_BUFFER.append("\n")

    OUTPUT_FILE_BUFFER.append("// %s" % CURTASK_SOURCE)
    OUTPUT_FILE_BUFFER.append(
        "void %s_CallbackBody( State* state, EngineInterface* ei, Task* task )"
        % (CURTASK_NAME)
    )
    OUTPUT_FILE_BUFFER.append("{")
    outputIdx = 0

    if len(CURTASK_CPU_PROFILE) > 0:
        OUTPUT_FILE_BUFFER.append(
            '    MICROPROFILE_SCOPEI( "vrdg", "%s", 0xFFFFFFFF );'
            % (CURTASK_CPU_PROFILE)
        )
    if len(CURTASK_GPU_PROFILE) > 0:
        OUTPUT_FILE_BUFFER.append(
            '    MICROPROFILE_SCOPEGPUI( "%s", 0xFFFFFFFF );' % (CURTASK_CPU_PROFILE)
        )

    for t, name, args in CURTASK_CREATE:
        if t.startswith("Create_Buffer"):
            OUTPUT_FILE_BUFFER.append(
                '    ei->CreateBuffer( task->output[task->createOutputIdx + %d], "%s"%s%s );'
                % (outputIdx, name, getSeparator(args), ", ".join(args))
            )
        if t.startswith("Create_TextureFB"):
            OUTPUT_FILE_BUFFER.append(
                '    ei->CreateFB( task->output[task->createOutputIdx + %d], "%s"%s%s );'
                % (outputIdx, name, getSeparator(args), ", ".join(args))
            )
        outputIdx = outputIdx + 1

    if len(CURTASK_FUNC) > 0:
        writeIdx = 0
        readIdx = 0
        for t, name, args in CURTASK_IO:
            if t.startswith("Write_Buffer"):
                OUTPUT_FILE_BUFFER.append(
                    "    auto %s = ei->GetEngineBufferObject( task->output[%d] );"
                    % (name, writeIdx)
                )
                writeIdx = writeIdx + 1
            if t.startswith("Write_TextureFB"):
                OUTPUT_FILE_BUFFER.append(
                    "    auto %s = ei->GetEngineFBObject( task->output[%d] );"
                    % (name, writeIdx)
                )
                writeIdx = writeIdx + 1
            if t.startswith("Read_Buffer"):
                OUTPUT_FILE_BUFFER.append(
                    "    auto %s = ei->GetEngineBufferObject( task->input[%d] );"
                    % (name, readIdx)
                )
                readIdx = readIdx + 1
            if t.startswith("Read_TextureFB"):
                OUTPUT_FILE_BUFFER.append(
                    "    auto %s = ei->GetEngineFBObject( task->input[%d] );"
                    % (name, readIdx)
                )
                readIdx = readIdx + 1
        OUTPUT_FILE_BUFFER.append("    %s( %s );" % (CURTASK_FUNC, ", ".join(callArgs)))
    OUTPUT_FILE_BUFFER.append("}\n")

    outputIdx = 0
    OUTPUT_FILE_BUFFER.append("// %s" % CURTASK_SOURCE)
    OUTPUT_FILE_BUFFER.append(
        "void %s( State* s%s%s )"
        % (CURTASK_NAME, getSeparator(inputArgs), ", ".join(inputArgs))
    )
    OUTPUT_FILE_BUFFER.append("{")
    OUTPUT_FILE_BUFFER.append("    Task task;")
    OUTPUT_FILE_BUFFER.append('    task.name = "%s";\n' % CURTASK_NAME)
    for t, name, args in CURTASK_IO:
        if t.startswith("Write_"):
            OUTPUT_FILE_BUFFER.append("    task.output.push_back( %s );" % name)
            OUTPUT_FILE_BUFFER.append(
                "    task.outputType.push_back( %s );\n" % IOTYPE_TO_ATTACH[t]
            )
            outputIdx = outputIdx + 1
        if t.startswith("Read_"):
            OUTPUT_FILE_BUFFER.append("    task.input.push_back( %s );" % name)
            OUTPUT_FILE_BUFFER.append(
                "    task.inputType.push_back( %s );\n" % IOTYPE_TO_ATTACH[t]
            )
    OUTPUT_FILE_BUFFER.append("    task.createOutputIdx = %d;\n" % outputIdx)
    for t, name, args in CURTASK_CREATE:
        OUTPUT_FILE_BUFFER.append("    %s = s->currentBuildPlaceholderID++;" % name)
        OUTPUT_FILE_BUFFER.append("    task.output.push_back( %s );" % name)
        OUTPUT_FILE_BUFFER.append(
            "    task.outputType.push_back( %s );\n" % IOTYPE_TO_ATTACH[t]
        )
    OUTPUT_FILE_BUFFER.append("    task.callback = %s_CallbackBody;" % CURTASK_NAME)
    if CURTASK_TYPE == "graphics":
        OUTPUT_FILE_BUFFER.append("    task.flags = VRDG_GRAPHICS;")
    else:
        OUTPUT_FILE_BUFFER.append("    task.flags = VRDG_COMPUTE;")
    OUTPUT_FILE_BUFFER.append("    s->tasks.push_back( task );")

    OUTPUT_FILE_BUFFER.append("}\n")

    return ""


def parseSourceFile(fileName):
    global CURTASK_SOURCE
    global CURTASK_NAME
    global CURTASK_TYPE
    global CURTASK_IO
    global CURTASK_CREATE
    global CURTASK_CPU_PROFILE
    global CURTASK_GPU_PROFILE
    global CURTASK_FUNC

    fp = open(fileName, "r", encoding="utf-8", errors="ignore")
    if not fp:
        print("Failed to open %s" % os.path.basename(fileName))

    lineIndex = -1
    for line in fp:
        lineIndex = lineIndex + 1
        if line.startswith("///>") == False:
            continue

        line = line.replace("///>", "").strip()
        lineArgs = getLineArguments(line)

        if len(line) == 0:
            continue

        if line.startswith("Graphics_Task") or line.startswith("Compute_Task"):
            CURTASK_NAME = lineArgs[0]
            CURTASK_SOURCE = (
                "Generated from definition in %s line %d. DO NOT EDIT HERE!"
                % (os.path.basename(fileName), lineIndex)
            )
            CURTASK_IO = []
            CURTASK_CREATE = []
            CURTASK_CPU_PROFILE = ""
            CURTASK_GPU_PROFILE = ""
            CURTASK_FUNC = ""
            if line.startswith("Graphics_Task"):
                CURTASK_TYPE = "graphics"
            else:
                CURTASK_TYPE = "compute"
        elif line.startswith("End_Task"):
            generateCurrentTask()
        elif line.startswith("Write_Buffer"):
            CURTASK_IO.append(("Write_Buffer", lineArgs[0], []))
        elif line.startswith("Read_Buffer"):
            CURTASK_IO.append(("Read_Buffer", lineArgs[0], []))
        elif line.startswith("Write_TextureFB"):
            CURTASK_IO.append(("Write_TextureFB", lineArgs[0], []))
        elif line.startswith("Read_TextureFB"):
            CURTASK_IO.append(("Read_TextureFB", lineArgs[0], []))
        elif line.startswith("Create_Buffer"):
            CURTASK_CREATE.append(("Create_Buffer", lineArgs[0], lineArgs[1:]))
        elif line.startswith("Create_TextureFB"):
            CURTASK_CREATE.append(("Create_TextureFB", lineArgs[0], lineArgs[1:]))
        elif line.startswith("CPU_Profile"):
            CURTASK_CPU_PROFILE = lineArgs[0]
        elif line.startswith("GPU_Profile"):
            CURTASK_GPU_PROFILE = lineArgs[0]
        elif line.startswith("Func"):
            CURTASK_FUNC = lineArgs[0]
        else:
            print("Failed understand: %s" % line)
            continue


# -------------------------------------------------- Main Script -----------------------------------------------------------

for file in glob.glob(sys.argv[1]):
    parseSourceFile(file)

OUTPUT_FILE_BUFFER.append("\n} // namespace vrdg\n")
for line in OUTPUT_FILE_BUFFER:
    print(line)
